---
- name: RouterOS test with network_cli connection
  hosts: routers
  gather_facts: false
  tasks:
    - name: Run a command
      community.routeros.command:
        commands:
          - /system resource print
          - /user add name=user2 group=read password=password123
          - /system ntp client set enabled=yes servers=0.ru.pool.ntp.org
          - /ip address add address=10.10.10.1/30 interface=ether3 network=10.10.10.0
          - /interface bridge add name=Loopback
          - /ip address add address=172.16.0.1 interface=Loopback network=172.16.0.1
          - /routing id add disabled=no id=172.16.0.1 name=OSPF_ID select-dynamic-id=""
          - /routing ospf instance add name=ospf-instance-1 originate-default=always route-id=OSPF_ID
          - /routing ospf instance area add instance=ospf-instance-1 name=Backbone
          - /routing ospf interface-template add area=Backbone auth=MD5 auth-key=admin interfaces=ether3
          - /routing ospf neighbor print
      register: system_resource_print
    - name: Print its output
      ansible.builtin.debug:
        var: system_resource_print.stdout_lines